/*
 * configmanager/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ConfigmanagerGetConfigRequest
 */
public class ConfigmanagerGetConfigRequestTest {
    private final ConfigmanagerGetConfigRequest model = new ConfigmanagerGetConfigRequest();

    /**
     * Model tests for ConfigmanagerGetConfigRequest
     */
    @Test
    public void testConfigmanagerGetConfigRequest() {
        // TODO: test ConfigmanagerGetConfigRequest
    }

    /**
     * Test the property 'tenantId'
     */
    @Test
    public void tenantIdTest() {
        // TODO: test tenantId
    }

    /**
     * Test the property 'key'
     */
    @Test
    public void keyTest() {
        // TODO: test key
    }

    /**
     * Test the property 'businessDomain'
     */
    @Test
    public void businessDomainTest() {
        // TODO: test businessDomain
    }

}
