/*
 * Config Manager Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ConfigmanagerGetTenantIdByCodeResponse
 */
public class ConfigmanagerGetTenantIdByCodeResponseTest {
    private final ConfigmanagerGetTenantIdByCodeResponse model = new ConfigmanagerGetTenantIdByCodeResponse();

    /**
     * Model tests for ConfigmanagerGetTenantIdByCodeResponse
     */
    @Test
    public void testConfigmanagerGetTenantIdByCodeResponse() {
        // TODO: test ConfigmanagerGetTenantIdByCodeResponse
    }

    /**
     * Test the property 'tenantId'
     */
    @Test
    public void tenantIdTest() {
        // TODO: test tenantId
    }

}
