/*
 * configmanager/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.BulkSetConfigsRequestConfig;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ConfigmanagerBulkSetConfigsRequest
 */
public class ConfigmanagerBulkSetConfigsRequestTest {
    private final ConfigmanagerBulkSetConfigsRequest model = new ConfigmanagerBulkSetConfigsRequest();

    /**
     * Model tests for ConfigmanagerBulkSetConfigsRequest
     */
    @Test
    public void testConfigmanagerBulkSetConfigsRequest() {
        // TODO: test ConfigmanagerBulkSetConfigsRequest
    }

    /**
     * Test the property 'tenantId'
     */
    @Test
    public void tenantIdTest() {
        // TODO: test tenantId
    }

    /**
     * Test the property 'configs'
     */
    @Test
    public void configsTest() {
        // TODO: test configs
    }

}
