/*
 * Config Manager Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import GeminiCommerce_Configmanager.ApiException;
import org.openapitools.client.model.ConfigmanagerBulkSetConfigsRequest;
import org.openapitools.client.model.ConfigmanagerConfigResponse;
import org.openapitools.client.model.ConfigmanagerGetConfigRequest;
import org.openapitools.client.model.ConfigmanagerGetTenantIdByCodeRequest;
import org.openapitools.client.model.ConfigmanagerGetTenantIdByCodeResponse;
import org.openapitools.client.model.RpcStatus;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ConfigManagerApi
 */
@Disabled
public class ConfigManagerApiTest {

    private final ConfigManagerApi api = new ConfigManagerApi();

    /**
     * BulkSetConfigs
     *
     * Bulk set configs
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void configManagerBulkSetConfigsTest() throws ApiException {
        ConfigmanagerBulkSetConfigsRequest body = null;
        Object response = api.configManagerBulkSetConfigs(body);
        // TODO: test validations
    }

    /**
     * GetConfig
     *
     * Get a config
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void configManagerGetConfigTest() throws ApiException {
        ConfigmanagerGetConfigRequest body = null;
        ConfigmanagerConfigResponse response = api.configManagerGetConfig(body);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void configManagerGetTenantIdByCodeTest() throws ApiException {
        ConfigmanagerGetTenantIdByCodeRequest body = null;
        ConfigmanagerGetTenantIdByCodeResponse response = api.configManagerGetTenantIdByCode(body);
        // TODO: test validations
    }

}
